modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/FinalJTth/&{mod_name}/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = "https://raw.githubusercontent.com/FinalJTth/ItemTagConverter/changelog/changelog.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/item-tag-converter"
credits = "Thanks to MattDahEpic and the entire open source mod community from which I used code."
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
