modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/FinalJTth/AutoOreDictConvert/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    updateJSONURL="https://raw.githubusercontent.com/MattDahEpic/Version/master/autooredictconv.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/auto-ore-dictionary-converter"
    credits="Thanks to the entire open source mod community from which I used code."
    authors="${mod_authors}"
    description='''${mod_description}'''

    [[dependencies.${mod_id}]]
        modId="forge"
        mandatory=true
        versionRange="${forge_version_range}"
        ordering="NONE"
        side="BOTH"
    [[dependencies.autooredictconv]]
        modId="minecraft"
        mandatory=true
        versionRange="${minecraft_version_range}"
        ordering="NONE"
        side="BOTH"
